#!/bin/bash

dotfiles=~/dotfiles/

# Zsh Setup is now managed by chezmoi
# See dot_zshenv, dot_config/zsh/dot_zshrc.tmpl, dot_config/zsh/dot_zlogin

# Nvim Setup is now managed by chezmoi
# See dot_config/nvim/

# Tmux Setup
if type "tmux" > /dev/null 2>&1; then
  echo -n 'Tmux installing .'

  ln -sf ${dotfiles}tmux/tmux.conf ~/.tmux.conf
  if type "git" > /dev/null 2>&1; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  fi

  echo ' ok!'
fi
