#!/bin/bash

dotfiles=~/dotfiles/

loader() {
  echo "### Dotfiles script ###"
  echo "if [[ -f $1 ]]; then"
  echo "  . $1"
  echo "fi"
  echo "### End ###"
}

# Bash Setup
if type "bash" > /dev/null 2>&1; then
  echo -n 'Bash installing .'

  maker() {
    if [[ -f ~/$1 ]]; then
      echo >> ~/$1
    fi
    loader "${dotfiles}bash/$1" >> ~/$1
    echo -n '.'
  }

  maker '.bash_profile'
  maker '.bashrc'
  echo ' ok!'
else
  echo "${0##*/}: Bash isn't found." 1>&2
fi

# Zsh Setup
if type "zsh" > /dev/null 2>&1; then
  echo -n 'Zsh installing .'

  maker() {
    if [[ -f ~/$1 ]]; then
      echo >> ~/$1
    fi
    loader "${dotfiles}zsh/$1" >> ~/$1
    echo -n '.'
  }

  maker '.zshenv'
  maker '.zlogin'
  maker '.zshrc'
  echo -n '.'

  # Sheldon config symlink
  sheldon_config_dir=~/.config/sheldon
  if [[ ! -d ${sheldon_config_dir} ]]; then
    mkdir -p ${sheldon_config_dir}
  fi
  ln -sf ${dotfiles}zsh/sheldon/plugins.toml ${sheldon_config_dir}/plugins.toml
  echo -n '.'

  echo ' ok!'
else
  echo "${0##*/}: Zsh isn't found." 1>&2
fi

# Nvim Setup (Modern Lua config)
# Legacy VimScript config (vim/.vimrc + dein.vim) is deprecated.
# See nvim/README.md for the new Lua-based configuration.
if type "nvim" > /dev/null 2>&1; then
  echo 'Setting up Neovim (Lua config)...'
  bash ${dotfiles}nvim/install.sh
else
  echo "${0##*/}: Neovim isn't found." 1>&2
fi

# Old Vim setup (commented out - migrated to Lua)
# nvim_comf_path=~/.config/nvim/
# if type "nvim" > /dev/null 2>&1; then
#   echo -n 'Neovim installing .'
#   mkdir -p ${nvim_comf_path}
#   ln -sf ${dotfiles}vim/.vimrc ${nvim_comf_path}init.vim
#   nvim -c 'cal dein#update()' -c 'qa!'
#   echo ' ok!'
# else
#   echo "${0##*/}: Neovim isn't found." 1>&2
# fi

# Tmux Setup
if type "tmux" > /dev/null 2>&1; then
  echo -n 'Tmux installing .'

  ln -sf ${dotfiles}tmux/.tmux.conf ~/.tmux.conf
  if type "git" > /dev/null 2>&1; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  fi

  echo ' ok!'
fi

