#!/bin/bash

dotfiles=~/dotfiles/

loader() {
  echo "### Dotfiles script ###"
  echo "if [[ -f $1 ]]; then"
  echo "  . $1"
  echo "fi"
  echo "### End ###"
}

# Zsh Setup
if type "zsh" > /dev/null 2>&1; then
  echo -n 'Zsh installing .'

  maker() {
    if [[ -f ~/$1 ]]; then
      echo >> ~/$1
    fi
    loader "${dotfiles}zsh/$1" >> ~/$1
    echo -n '.'
  }

  maker 'zshenv'
  maker 'zlogin'
  maker 'zshrc'
  echo -n '.'

  # Sheldon config is now managed by chezmoi (dot_config/sheldon/plugins.toml)
  # No symlink needed

  echo ' ok!'
else
  echo "${0##*/}: Zsh isn't found." 1>&2
fi

# Nvim Setup (Modern Lua config)
# Legacy VimScript config (vim/.vimrc + dein.vim) is deprecated.
# See nvim/README.md for the new Lua-based configuration.
if type "nvim" > /dev/null 2>&1; then
  echo 'Setting up Neovim (Lua config)...'
  bash ${dotfiles}nvim/install.sh
else
  echo "${0##*/}: Neovim isn't found." 1>&2
fi

# Tmux Setup
if type "tmux" > /dev/null 2>&1; then
  echo -n 'Tmux installing .'

  ln -sf ${dotfiles}tmux/tmux.conf ~/.tmux.conf
  if type "git" > /dev/null 2>&1; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  fi

  echo ' ok!'
fi
