# PATH: DOTFILES/bin, ~/.local/bin, ~/.cargo/bin
# DOTFILES was generated by a chezmoi template (.chezmoi.config.sourceDir) for a
# deterministic source root. dotfiles apply has no chezmoi to resolve it, and no
# replacement source is decided yet, so the line is disabled for now instead of
# silently dropping the feature.
# set -gx DOTFILES "???"

# Homebrew (macOS) — /etc/paths.d/homebrew appends /opt/homebrew/bin after
# /usr/bin, so prepend explicitly to override system tools.
if test -d /opt/homebrew
    fish_add_path --global --prepend --move /opt/homebrew/sbin
    fish_add_path --global --prepend --move /opt/homebrew/bin
end

# Prepend in this order so effective search order is: dotfiles, then ~/.local/bin, then cargo, then homebrew.
fish_add_path --global --prepend --move $HOME/.cargo/bin
fish_add_path --global --prepend --move $HOME/.local/bin
# fish_add_path --global --prepend --move "$DOTFILES/bin"

# Obsidian (macOS only)
if test -d /Applications/Obsidian.app/Contents/MacOS
    fish_add_path --global --append /Applications/Obsidian.app/Contents/MacOS
end
