[merge_ready]
symbol = "󰄬"

[conflict]
symbol = ""

[update_branch]
symbol = "󰚰"

[sync_unknown]
symbol = ""

[ci_fail]
symbol = ""

[ci_action]
symbol = "󰀦"

[changes_requested]
symbol = "󰀦"

[no_pull_request]
symbol = "󰎔"

[error]
symbol = ""

