name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release
    # Knope が作成した Release PR がマージされたときのみ実行する。
    if: github.head_ref == 'release' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Install Knope
        uses: knope-dev/action@v2.1.2
        with:
          version: 0.23.0

      - name: Release
        run: knope release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
